apiVersion: v1
kind: Service
metadata:
  name: url-checker-service
  labels:
    app: url-checker
spec:
  type: NodePort
  selector:
    app: url-checker
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: metrics-port
      nodePort: 30066
